Collections:
  - Name: CenterPoint
    Metadata:
      Training Data: nuScenes
      Training Techniques:
        - AdamW
      Training Resources: 8x V100 GPUs
      Architecture:
        - Hard Voxelization
    Paper:
      URL: https://arxiv.org/abs/2006.11275
      Title: 'Center-based 3D Object Detection and Tracking'
    README: configs/centerpoint/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/detectors/centerpoint.py#L10
      Version: v0.6.0

Models:
  - Name: centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus
    In Collection: CenterPoint
    Config: configs/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py
    Metadata:
      Training Memory (GB): 5.2
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 56.11
          NDS: 64.61
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus_20220810_030004-9061688e.pth

  - Name: centerpoint_01voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus
    In Collection: CenterPoint
    Config: configs/centerpoint/centerpoint_01voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py
    Metadata:
      Training Memory (GB): 5.5
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 56.10
          NDS: 64.69
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_01voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus/centerpoint_01voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20220810_052355-a6928835.pth

  - Name: centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus
    In Collection: CenterPoint
    Config: configs/centerpoint/centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py
    Metadata:
      Training Memory (GB): 8.2
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 56.54
          NDS: 65.17
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus/centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus_20220810_011659-04cb3a3b.pth

  - Name: centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus
    In Collection: CenterPoint
    Config: configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py
    Metadata:
      Training Memory (GB): 8.7
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 56.92
          NDS: 65.27
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20220810_025930-657f67e0.pth

  - Name: centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus
    In Collection: CenterPoint
    Config: configs/centerpoint/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus.py
    Metadata:
      Training Memory (GB): 4.6
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 48.70
          NDS: 59.62
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus_20220811_031844-191a3822.pth

  - Name: centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus
    In Collection: CenterPoint
    Config: configs/centerpoint/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus.py
    Metadata:
      Training Memory (GB): 4.9
    Results:
      - Task: 3D Object Detection
        Dataset: nuScenes
        Metrics:
          mAP: 48.38
          NDS: 59.79
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus_20220811_045458-808e69ad.pth
