blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/open-mmlab/mmdetection3d/discussions
    about: Ask general usage questions and discuss with other MMDetection3d community members
  - name: ğŸŒ Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
