Collections:
  - Name: Dynamic Voxelization
    Metadata:
      Training Data: KITTI
      Training Techniques:
        - AdamW
      Training Resources: 8x V100 GPUs
      Architecture:
        - Dynamic Voxelization
    Paper:
      URL: https://arxiv.org/abs/1910.06528
      Title: 'End-to-End Multi-View Fusion for 3D Object Detection in LiDAR Point Clouds'
    README: configs/dynamic_voxelization/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/detectors/dynamic_voxelnet.py#L11
      Version: v0.5.0

Models:
  - Name: dv_second_secfpn_6x8_80e_kitti-3d-car
    In Collection: Dynamic Voxelization
    Config: configs/dynamic_voxelization/dv_second_secfpn_6x8_80e_kitti-3d-car.py
    Metadata:
      Training Memory (GB): 5.5
    Results:
      - Task: 3D Object Detection
        Dataset: KITTI
        Metrics:
          mAP: 78.83
    Weights: https://download.openmmlab.com/mmdetection3d/v0.1.0_models/dynamic_voxelization/dv_second_secfpn_6x8_80e_kitti-3d-car/dv_second_secfpn_6x8_80e_kitti-3d-car_20200620_235228-ac2c1c0c.pth

  - Name: dv_second_secfpn_2x8_cosine_80e_kitti-3d-3class
    In Collection: Dynamic Voxelization
    Config: configs/dynamic_voxelization/dv_second_secfpn_2x8_cosine_80e_kitti-3d-3class.py
    Metadata:
      Training Memory (GB): 5.5
    Results:
      - Task: 3D Object Detection
        Dataset: KITTI
        Metrics:
          mAP: 65.27
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/dynamic_voxelization/dv_second_secfpn_2x8_cosine_80e_kitti-3d-3class/dv_second_secfpn_2x8_cosine_80e_kitti-3d-3class_20210831_054106-e742d163.pth

  - Name: dv_pointpillars_secfpn_6x8_160e_kitti-3d-car
    In Collection: Dynamic Voxelization
    Config: configs/dynamic_voxelization/dv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py
    Metadata:
      Training Memory (GB): 4.7
    Results:
      - Task: 3D Object Detection
        Dataset: KITTI
        Metrics:
          mAP: 77.76
    Weights: https://download.openmmlab.com/mmdetection3d/v0.1.0_models/dynamic_voxelization/dv_pointpillars_secfpn_6x8_160e_kitti-3d-car/dv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20200620_230844-ee7b75c9.pth
