Collections:
  - Name: VoteNet
    Metadata:
      Training Techniques:
        - AdamW
      Training Resources: 8x V100 GPUs
      Architecture:
        - PointNet++
    Paper:
      URL: https://arxiv.org/abs/1904.09664
      Title: 'Deep Hough Voting for 3D Object Detection in Point Clouds'
    README: configs/votenet/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/detectors/votenet.py#L10
      Version: v0.5.0

Models:
  - Name: votenet_16x8_sunrgbd-3d-10class
    In Collection: VoteNet
    Config: configs/votenet/votenet_16x8_sunrgbd-3d-10class.py
    Metadata:
      Training Data: SUNRGBD
      Training Memory (GB): 8.1
    Results:
      - Task: 3D Object Detection
        Dataset: SUNRGBD
        Metrics:
          AP@0.25: 59.78
          AP@0.5: 35.77
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/votenet/votenet_16x8_sunrgbd-3d-10class/votenet_16x8_sunrgbd-3d-10class_20210820_162823-bf11f014.pth

  - Name: votenet_8x8_scannet-3d-18class
    In Collection: VoteNet
    Config: configs/votenet/votenet_8x8_scannet-3d-18class.py
    Metadata:
      Training Data: ScanNet
      Training Memory (GB): 4.1
    Results:
      - Task: 3D Object Detection
        Dataset: ScanNet
        Metrics:
          AP@0.25: 62.34
          AP@0.5: 40.82
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/votenet/votenet_8x8_scannet-3d-18class/votenet_8x8_scannet-3d-18class_20210823_234503-cf8134fa.pth

  - Name: votenet_iouloss_8x8_scannet-3d-18class
    In Collection: VoteNet
    Config: configs/votenet/votenet_iouloss_8x8_scannet-3d-18class.py
    Metadata:
      Training Data: ScanNet
      Training Memory (GB): 4.1
      Architecture:
        - IoU Loss
    Results:
      - Task: 3D Object Detection
        Dataset: ScanNet
        Metrics:
          AP@0.25: 63.81
          AP@0.5: 44.21
    Weights: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/votenet/votenet_8x8_scannet-3d-18class/votenet_8x8_scannet-3d-18class_20210823_234503-cf8134fa.pth
